# Generated by Django 3.0.2 on 2020-04-24 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 3, 19, 29, 454769, tzinfo=utc)),
        ),
    ]
