# Generated by Django 2.2.4 on 2019-09-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20190926_0203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='NoteFile',
        ),
    ]
