# Generated by Django 3.0.2 on 2020-04-24 03:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 4, 24, 3, 15, 35, 268324, tzinfo=utc))),
            ],
        ),
    ]
