# Generated by Django 3.0.5 on 2020-04-30 20:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qary_app', '0002_auto_20200428_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('url', models.URLField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 20, 20, 15, 193204, tzinfo=utc)),
        ),
    ]
