# Generated by Django 3.0.5 on 2020-05-04 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qary_app', '0003_auto_20200430_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 4, 5, 26, 913657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
