# Generated by Django 3.0.5 on 2020-05-08 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qary_app', '0006_auto_20200508_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 6, 10, 2, 274496, tzinfo=utc)),
        ),
    ]
