# Generated by Django 3.0.5 on 2020-05-08 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qary_app', '0007_auto_20200508_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 6, 13, 55, 962801, tzinfo=utc)),
        ),
    ]
